#!/bin/sh
#
# @name Generic Iris Quadrotor SITL
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.042
param set-default CA_ROTOR0_PY 0.068
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.042
param set-default CA_ROTOR1_PY -0.052
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.042
param set-default CA_ROTOR2_PY -0.068
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.042
param set-default CA_ROTOR3_PY 0.052
param set-default CA_ROTOR3_KM -0.05

# param set-default MC_PITCHRATE_D 0.000500000023748726
# param set-default MC_PITCHRATE_I 0.000
# param set-default MC_PITCHRATE_MAX 1200.0
# param set-default MC_PITCHRATE_P 0.050000000745058060
# param set-default MC_PITCHRATE_K 1.10000000000000000
# param set-default MC_PITCH_P 5.00
# param set_default MC_PR_INIT_LIM 0.3000000000000000

# param set-default MC_ROLLRATE_D 0.000500000023748726
# param set-default MC_ROLLRATE_I 0.000
# param set-default MC_ROLLRATE_MAX 1200.0
# param set-default MC_ROLLRATE_P 0.050000000745058060
# param set-default MC_ROLLRATE_K 1.100000000000000
# param set-default MC_ROLL_P 5.00
# param set_default MC_RR_INIT_LIM 0.3000000000000000

# param set-default MC_YAW_P 3.000000190734863281
# param set-default MC_YAWRATE_D 0.0000000000000000
# param set-default MC_YAWRATE_I 0.000500000000000000
# param set-default MC_YAWRATE_K 1.100000000000000
# param set-default MC_YAWRATE_MAX 1200.000000000000000
# param set-default MC_YAWRATE_P 0.07000000000000000
# param set-default MC_YAW_WEIGHT 0.400000005960464478

# param set-default MPC_XY_P 6.8
# param set-default MPC_XY_P 6.20
# param set_default MPC_XY_VEL_P_ACC 6.30
# param set-default MPC_XY_P 5.20
# param set_default MPC_XY_VEL_P_ACC 5.30
param set-default MPC_XY_P 4.50
param set-default MPC_Z_P 2.80
param set-default MPC_XY_TRAJ_P 1.0
# param set_default MPC_XY_VEL_P_ACC 4.0
param set_default MPC_XY_VEL_P_ACC 4.5
# param set_default MPC_XY_VEL_P_ACC 6.5
param set-default MPC_XY_VEL_D_ACC 0.3
param set-default MPC_THR_HOVER 0.168
param set-default MPC_XY_VEL_I_ACC 0.0
# param set-default MC_YAW_P 0.90
param set-default MC_YAWRATE_I 0.0
# param set-default MC_YAW_WEIGHT 0.36
# param set-default MC_ROLL_WEIGHT 0.32
# param set-default MC_PITCH_WEIGHT 0.32
# param set-default MC_ROLL_P 6.50
# param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.0
# param set-default MC_PITCH_P 6.50
# param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.0
param set-default MPC_THR_MIN 0.10

# param set-default MPC_USE_HTE 0
# param set-default MC_YAWRATE_D 0.0
# param set-default MC_YAWRATE_I 0.12
# param set-default MC_YAWRATE_P 0.12
# param set-default MC_YAW_P 6.5
# param set-default MC_PITCHRATE_D 0.0037
# param set-default MC_PITCHRATE_I 0.271
# param set-default MC_PITCHRATE_P 0.202
# param set-default MC_PITCH_P 4.74
# param set-default MC_ROLLRATE_D 0.004
# param set-default MC_ROLLRATE_I 0.265
# param set-default MC_ROLL_P 4.85

# param set-default MC_AT_EN 1



param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
