#!/bin/sh
#
# @name Generic Iris Quadrotor SITL
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.042
param set-default CA_ROTOR0_PY 0.068
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.042
param set-default CA_ROTOR1_PY -0.052
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.042
param set-default CA_ROTOR2_PY -0.068
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.042
param set-default CA_ROTOR3_PY 0.052
param set-default CA_ROTOR3_KM -0.05

param set-default MPC_XY_P 4.50
# param set-default MPC_Z_P 3.50
param set-default MPC_Z_P 2.50
param set-default MPC_XY_TRAJ_P 1.0
# param set_default MPC_XY_VEL_P_ACC 4.0
# param set_default MPC_XY_VEL_P_ACC 4.5
param set_default MPC_XY_VEL_P_ACC 6.5
param set-default MPC_XY_VEL_D_ACC 0.5
# param set-default MPC_XY_VEL_D_ACC 0.3
# param set-default MPC_THR_HOVER 0.20
param set-default MPC_THR_HOVER 0.1680
param set-default MPC_XY_VEL_I_ACC 0.20
param set-default MPC_Z_VEL_I_ACC 1.750
param set-default MC_YAW_P 0.90
# param set-default MC_YAWRATE_I 0.03
param set-default MC_YAWRATE_I 0.0

param set-default MC_ROLLRATE_I 0.0
# param set-default MC_PITCH_P 6.50
# param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.0
param set-default MPC_THR_MIN 0.10



param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
