#!/bin/sh
#
# @name Gazebo charpi vision
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=charpi_vision}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotor positions (NED body frame, metres) measured from charpi URDF.
# rotor 0: front-right (CCW)
param set-default CA_ROTOR0_PX  0.10
param set-default CA_ROTOR0_PY  0.10
param set-default CA_ROTOR0_KM  0.05

# rotor 1: rear-left (CCW)
param set-default CA_ROTOR1_PX -0.10
param set-default CA_ROTOR1_PY -0.10
param set-default CA_ROTOR1_KM  0.05

# rotor 2: front-left (CW)
param set-default CA_ROTOR2_PX  0.10
param set-default CA_ROTOR2_PY -0.10
param set-default CA_ROTOR2_KM -0.05

# rotor 3: rear-right (CW)
param set-default CA_ROTOR3_PX -0.10
param set-default CA_ROTOR3_PY  0.10
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Mass ~1.29 kg, motorConstant 2.3e-5
param set-default MPC_THR_HOVER 0.70
param set-default MPC_TKO_SPEED 1.5
param set-default MPC_LAND_SPEED 0.5

# ---- Multicopter rate & attitude controller tuning (from real drone) ----
param set-default MC_ROLL_P  6.5
param set-default MC_PITCH_P 6.5
param set-default MC_YAW_P   2.8

param set-default MC_ROLLRATE_K   0.6
param set-default MC_ROLLRATE_P   0.1
param set-default MC_ROLLRATE_I   0.15
param set-default MC_ROLLRATE_D   0.0018
param set-default MC_ROLLRATE_FF  0.0
param set-default MC_ROLLRATE_MAX 220
param set-default MC_RR_INT_LIM   0.3

param set-default MC_PITCHRATE_K   0.6
param set-default MC_PITCHRATE_P   0.15
param set-default MC_PITCHRATE_I   0.15
param set-default MC_PITCHRATE_D   0.0024
param set-default MC_PITCHRATE_FF  0.0
param set-default MC_PITCHRATE_MAX 220
param set-default MC_PR_INT_LIM    0.3

param set-default MC_YAWRATE_K   0.5
param set-default MC_YAWRATE_P   0.2
param set-default MC_YAWRATE_I   0.1
param set-default MC_YAWRATE_D   0.0
param set-default MC_YAWRATE_FF  0.0
param set-default MC_YAWRATE_MAX 200
param set-default MC_YAW_WEIGHT  0.4

# ---- Other "safe" params imported from real drone (no SITL conflict) ----
# Battery (6S LiPo)
param set-default BAT1_N_CELLS    6
param set-default BAT1_V_EMPTY    3.7
param set-default BAT1_V_CHARGED  4.05
param set-default BAT_LOW_THR     0.25
param set-default BAT_CRIT_THR    0.07
param set-default BAT_EMERGEN_THR 0.05
param set-default BAT_AVRG_CURRENT 15.0

# Acro mode tuning
param set-default MC_ACRO_EXPO     0.0
param set-default MC_ACRO_EXPO_Y   0.0
param set-default MC_ACRO_SUPEXPO  0.0
param set-default MC_ACRO_SUPEXPOY 0.0
param set-default MC_ACRO_P_MAX    100
param set-default MC_ACRO_R_MAX    100
param set-default MC_ACRO_Y_MAX    100

# Takeoff/landing speeds and ramp
param set-default MPC_TKO_RAMP_T 3.0
param set-default MPC_LAND_SPEED 0.7

# Return-to-launch behaviour
param set-default RTL_DESCEND_ALT  10.0
param set-default RTL_RETURN_ALT   30.0
param set-default RTL_MIN_DIST     10.0
param set-default RTL_CONE_ANG     45
param set-default RTL_LOITER_RAD   80.0
param set-default RTL_LAND_DELAY   0.0
param set-default RTL_TIME_FACTOR  1.1
param set-default RTL_TIME_MARGIN  100
param set-default RTL_APPR_FORCE   0
param set-default RTL_PLD_MD       0
param set-default RTL_TYPE         0

# Logging profile (matches real drone for consistent post-flight analysis)
param set-default SDLOG_PROFILE 17

param set-default NAV_DLL_ACT 2
